# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vorname', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(verbose_name='joined date')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Gym')),
            ],
        ),
    ]
